from enum import Enum #, unique
from binance.client import Client 

#@unique
class KlineInterval(Enum):
    ONE_MIN = Client.KLINE_INTERVAL_1MINUTE
    THREE_MIN = Client.KLINE_INTERVAL_3MINUTE 
    FIVE_MIN = Client.KLINE_INTERVAL_5MINUTE
    FIFTEEN_MIN = Client. KLINE_INTERVAL_15MINUTE
    THIRTY_MIN = Client.KLINE_INTERVAL_30MINUTE
    ONE_HOUR = Client.KLINE_INTERVAL_1HOUR
    TWO_HOURS = Client.KLINE_INTERVAL_2HOUR
    FOUR_HOURS = Client.KLINE_INTERVAL_4HOUR
    SIX_HOURS = Client.KLINE_INTERVAL_6HOUR
    EIGHT_HOURS = Client.KLINE_INTERVAL_8HOUR
    TWELVE_HOURS = Client.KLINE_INTERVAL_12HOUR
    ONE_DAY = Client.KLINE_INTERVAL_1DAY
    THREE_DAYS = Client.KLINE_INTERVAL_3DAY
    ONE_WEEK = Client.KLINE_INTERVAL_1WEEK
    ONE_MONTH = Client.KLINE_INTERVAL_1MONTH
    